version: "3"
services:
  server-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - awesome
    environment:
      - DB_HOSTNAME=postgres
  postgres:
    build:
        context: ./db
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=postgres
    restart: always
    networks:
      - awesome
networks:
    awesome:
        driver: bridge 