name: Create Pull Request
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  Run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests 
      run: npm test
