name: Create Pull Request
on:
  pull_request:
    branches:
      - feature/sprint9/cicd
    types: [opened, synchronize]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up node 
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: npm ci
    - name: Run unit tests 
      run: npm test
