name: On Merging Pull Request
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_YANDEX_PRIVATE_KEY }}
        script: |
          cd ~/game && git checkout main && git pull
          docker compose down
          docker compose up -d